export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";

export const MINING_START = "MINING_START";
export const MINING_STOP = "MINING_STOP";
